### ISSUE TITLE
Revenge 223+ support

### ISSUE THREAD

**Issue by rezamadness** [revenge-mod/Revenge-old#42]
The app won't launch anymore after updating to stable v223.15. Reinstalling doesn't help either

**Comment by riivx** [comment]
please do not update to 223+ yet - we're aware of the problem and working on it.

if you've already updated - set version number to previous version (222013 for stable), backup your plugins (if it's possible), delete revenge and install old version.

**Comment by Big-Iron-Cheems** [comment]
I can't seem to downgrade after uninstalling the app at all. I have selected both the custom package name and version in the developer settings.

Keeps saying:
`04-03-2024 9:44:56AM [E] INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME: Invalid manifest package: bad character ':'`

Logs attached.
[VD-Manager-1712130177088.log.txt](https://github.com/revenge-mod/Revenge/files/14848609/VD-Manager-1712130177088.log.txt)

**Comment by puhbu** [comment]
Looking just at the error you've said it seems you have a : in the package name? What is your custom package name?

**Comment by riivx** [comment]
where did you put the link?

**Comment by Big-Iron-Cheems** [comment]
Oh god, I saw the mistake just now... That was supposed to be used in the app itself, not the manager.

What's the dafault package name in the dev settings?

**Comment by Starcalled** [comment]
I believe the default is `dev.beefers.vendetta`, or at least that's what it's set to for me.

**Comment by dimaguy** [comment]
On more recent android versions, apps can add quick launch options to be shown when holding the app icon in the launcher. Could there be a safe mode launch for situations like this?

Should I open a separate issue for this suggestion?

**Comment by riivx** [comment]
it can be done only by adding like a clone of the app or something
even if we manage to somehow reinstall all split apks on the go, we still have to keep not just the last, but two of them (current version and previous one)

**Comment by itsthejoker** [comment]
@dimaguy can confirm, OG crashes on page load now. I also can't seem to roll back, so I suppose I'm in a holding pattern for now. 😩

**Comment by h4rldev** [comment]
Yeah, downgrading still doesn't work

**Comment by dimaguy** [comment]
> @dimaguy can confirm, OG crashes on page load now. I also can't seem to roll back, so I suppose I'm in a holding pattern for now. 😩

Rolling back isn't allowed by android itself, you'd need to tweak discord apk's version number for that

**Comment by rezamadness** [comment]
As the first reply had mentioned versions past 223 don't work with Revenge. I managed to roll back to v222.13 by typing in the desired version in the Discord version text box.
![Screenshot_20240404_161144_Vendetta Manager](https://github.com/revenge-mod/Revenge/assets/97009491/f080313d-c63c-464d-a11d-d65893c6ebbe)

**Comment by h4rldev** [comment]
It tells you that in manager, and 222 doesn't work either
